version: 0.0.0.{build}

# Build worker image (VM template)
image: Visual Studio 2017

assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
  
# tasks
before_build:
- cmd: .paket\paket.exe restore

build_script:
- cmd: >-
    ./build.bat all

on_success:
  - ps: ./sendwebhook.ps1 success $env:WEBHOOK_URL
on_failure:
  - ps: ./sendwebhook.ps1 failure $env:WEBHOOK_URL


test: off

artifacts:
- path: artifacts
  name: evealod
